# Site settings
title: senseBox | Die Kiste mit Sinn
email: info@sensebox.de
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sensebox.de/" # the base hostname & protocol for your site
twitter_username: sensebox_de
github_username: sensebox
facebook_username: sensebox.de

# Build settings
markdown: kramdown

# Blog pagination
paginate: 5
paginate_path: "/news/page/:num"

# Extra styling
# sass:
#   # loading path from site root
#   # default to _sass
#   sass_dir: bower_components/bootstrap-sass/assets/stylesheets

#   # style : nested (default), compact, compressed, expanded
#   #         :nested, :compact, :compressed, :expanded also works
#   # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
#   # on a typical twitter bootstrap stats are :
#   # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
#   style: compressed

exclude:
#  - bower_components
  - vendor

collections:
  - press
  - awards
  - awards_en
  - events

gems:
  - jekyll-redirect-from
